services:
    bs.rapi.request:
        class: RAPIBundle\Request\Request
        arguments: [@request_stack]

    bs.rapi.response:
        class: RAPIBundle\Response\Response

    bs.rapi.mapper:
        class: RAPIBundle\DataMapper\Mapper
        abstract:  true

    bs.rapi.data_mapper:
        class: RAPIBundle\DataMapper\DataMapper
        parent: bs.rapi.mapper
